# Generated by Django 5.0.8 on 2024-08-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_myuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='tokens',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
