# Generated by Django 5.0.8 on 2024-10-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_myuser_tokens_alter_myuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorie',
            name='carbohydrates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calorie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calorie',
            name='fats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calorie',
            name='proteins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calorie',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
