# Generated by Django 5.0.8 on 2024-11-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_calorie_carbohydrates_calorie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
