# Generated by Django 5.0.8 on 2024-11-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_myuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='language',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
